//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanManager.Server.ResourceSet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanManager.Server.ResourceSet.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Tab.
        /// </summary>
        internal static string AddAdminTab {
            get {
                return ResourceManager.GetString("AddAdminTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        internal static string AddClientTab {
            get {
                return ResourceManager.GetString("AddClientTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName or Password invalid.
        /// </summary>
        internal static string AdminLogOnInvalid {
            get {
                return ResourceManager.GetString("AdminLogOnInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string AppActive {
            get {
                return ResourceManager.GetString("AppActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Path.
        /// </summary>
        internal static string AppDefaultPath {
            get {
                return ResourceManager.GetString("AppDefaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Age.
        /// </summary>
        internal static string AppMinimumAge {
            get {
                return ResourceManager.GetString("AppMinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Admin.
        /// </summary>
        internal static string ButtonAddAdmin {
            get {
                return ResourceManager.GetString("ButtonAddAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add App.
        /// </summary>
        internal static string ButtonAddApp {
            get {
                return ResourceManager.GetString("ButtonAddApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        internal static string ButtonAddClient {
            get {
                return ResourceManager.GetString("ButtonAddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        internal static string ButtonAddGroup {
            get {
                return ResourceManager.GetString("ButtonAddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOn.
        /// </summary>
        internal static string ButtonLogOn {
            get {
                return ResourceManager.GetString("ButtonLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string CheckActive {
            get {
                return ResourceManager.GetString("CheckActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by date.
        /// </summary>
        internal static string CheckFilterByDate {
            get {
                return ResourceManager.GetString("CheckFilterByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New client registered.
        /// </summary>
        internal static string ClientAdded {
            get {
                return ResourceManager.GetString("ClientAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Document ID.
        /// </summary>
        internal static string InvalidDocumentId {
            get {
                return ResourceManager.GetString("InvalidDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string LabelActive {
            get {
                return ResourceManager.GetString("LabelActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Age:.
        /// </summary>
        internal static string LabelAge {
            get {
                return ResourceManager.GetString("LabelAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments:.
        /// </summary>
        internal static string LabelArg {
            get {
                return ResourceManager.GetString("LabelArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BirthDate:.
        /// </summary>
        internal static string LabelBirthDate {
            get {
                return ResourceManager.GetString("LabelBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Access Any App:.
        /// </summary>
        internal static string LabelCanAccessAnyApp {
            get {
                return ResourceManager.GetString("LabelCanAccessAnyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Access Any Time:.
        /// </summary>
        internal static string LabelCanAccessAnyTime {
            get {
                return ResourceManager.GetString("LabelCanAccessAnyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        internal static string LabelCity {
            get {
                return ResourceManager.GetString("LabelCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        internal static string LabelCountry {
            get {
                return ResourceManager.GetString("LabelCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Id:.
        /// </summary>
        internal static string LabelDocumentId {
            get {
                return ResourceManager.GetString("LabelDocumentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name:.
        /// </summary>
        internal static string LabelFatherName {
            get {
                return ResourceManager.GetString("LabelFatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        internal static string LabelFullName {
            get {
                return ResourceManager.GetString("LabelFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        internal static string LabelGroup {
            get {
                return ResourceManager.GetString("LabelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Midnight Permission:.
        /// </summary>
        internal static string LabelHasMidnightPermission {
            get {
                return ResourceManager.GetString("LabelHasMidnightPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image:.
        /// </summary>
        internal static string LabelImage {
            get {
                return ResourceManager.GetString("LabelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Debit:.
        /// </summary>
        internal static string LabelMaxDebit {
            get {
                return ResourceManager.GetString("LabelMaxDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes Bonus:.
        /// </summary>
        internal static string LabelMinutesBonus {
            get {
                return ResourceManager.GetString("LabelMinutesBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes Left:.
        /// </summary>
        internal static string LabelMinutesLeft {
            get {
                return ResourceManager.GetString("LabelMinutesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone:.
        /// </summary>
        internal static string LabelMobilePhone {
            get {
                return ResourceManager.GetString("LabelMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Name:.
        /// </summary>
        internal static string LabelMotherName {
            get {
                return ResourceManager.GetString("LabelMotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname:.
        /// </summary>
        internal static string LabelNickname {
            get {
                return ResourceManager.GetString("LabelNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string LabelPath {
            get {
                return ResourceManager.GetString("LabelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string LabelPhone {
            get {
                return ResourceManager.GetString("LabelPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Client:.
        /// </summary>
        internal static string LabelPrincipal {
            get {
                return ResourceManager.GetString("LabelPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School:.
        /// </summary>
        internal static string LabelSchool {
            get {
                return ResourceManager.GetString("LabelSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolTime:.
        /// </summary>
        internal static string LabelSchoolTime {
            get {
                return ResourceManager.GetString("LabelSchoolTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        internal static string LabelState {
            get {
                return ResourceManager.GetString("LabelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address:.
        /// </summary>
        internal static string LabelStreetAddress {
            get {
                return ResourceManager.GetString("LabelStreetAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string LabelUserName {
            get {
                return ResourceManager.GetString("LabelUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip:.
        /// </summary>
        internal static string LabelZip {
            get {
                return ResourceManager.GetString("LabelZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Admins.
        /// </summary>
        internal static string ManageAdminsButton {
            get {
                return ResourceManager.GetString("ManageAdminsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Groups.
        /// </summary>
        internal static string ManageAppGroupsButton {
            get {
                return ResourceManager.GetString("ManageAppGroupsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Apps.
        /// </summary>
        internal static string ManageAppsButton {
            get {
                return ResourceManager.GetString("ManageAppsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Clients.
        /// </summary>
        internal static string ManageClientsButton {
            get {
                return ResourceManager.GetString("ManageClientsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Admin username exists.
        /// </summary>
        internal static string MessageAdminExists {
            get {
                return ResourceManager.GetString("MessageAdminExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number.
        /// </summary>
        internal static string MessageBoxInteger {
            get {
                return ResourceManager.GetString("MessageBoxInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username exists.
        /// </summary>
        internal static string MessageClientExists {
            get {
                return ResourceManager.GetString("MessageClientExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string MessageContinue {
            get {
                return ResourceManager.GetString("MessageContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document id already exists.
        /// </summary>
        internal static string MessageDocumentIdExists {
            get {
                return ResourceManager.GetString("MessageDocumentIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string ReportDurationColumn {
            get {
                return ResourceManager.GetString("ReportDurationColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string ReportEndDateColumn {
            get {
                return ResourceManager.GetString("ReportEndDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        internal static string ReportFullNameColumn {
            get {
                return ResourceManager.GetString("ReportFullNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportsTab {
            get {
                return ResourceManager.GetString("ReportsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string ReportStartDateColumn {
            get {
                return ResourceManager.GetString("ReportStartDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Student.
        /// </summary>
        internal static string SchoolTime0 {
            get {
                return ResourceManager.GetString("SchoolTime0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        internal static string SchoolTime1 {
            get {
                return ResourceManager.GetString("SchoolTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afternoon.
        /// </summary>
        internal static string SchoolTime2 {
            get {
                return ResourceManager.GetString("SchoolTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string SchoolTime3 {
            get {
                return ResourceManager.GetString("SchoolTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchTab {
            get {
                return ResourceManager.GetString("SearchTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string SessionsTab {
            get {
                return ResourceManager.GetString("SessionsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
