//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanManager.BLL.ResourceSet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanManager.BLL.ResourceSet.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait 30 minutes between each session.
        /// </summary>
        internal static string Client30MinutesPermission {
            get {
                return ResourceManager.GetString("Client30MinutesPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client is already logged.
        /// </summary>
        internal static string ClientAlreadyLogged {
            get {
                return ResourceManager.GetString("ClientAlreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don´t have credits.
        /// </summary>
        internal static string ClientCreditLimit {
            get {
                return ResourceManager.GetString("ClientCreditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can´t logon this hour.
        /// </summary>
        internal static string ClientHourPermission {
            get {
                return ResourceManager.GetString("ClientHourPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This client isn´t active.
        /// </summary>
        internal static string ClientInactive {
            get {
                return ResourceManager.GetString("ClientInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can´t logon between 00:00 AM and 06:00 AM.
        /// </summary>
        internal static string ClientMidnightPermission {
            get {
                return ResourceManager.GetString("ClientMidnightPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is outdated, tell it to the manager to update their data.
        /// </summary>
        internal static string ClientOutDated {
            get {
                return ResourceManager.GetString("ClientOutDated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This access point don´t exists.
        /// </summary>
        internal static string InvalidAccessPointId {
            get {
                return ResourceManager.GetString("InvalidAccessPointId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password invalid.
        /// </summary>
        internal static string InvalidLogOn {
            get {
                return ResourceManager.GetString("InvalidLogOn", resourceCulture);
            }
        }
    }
}
